name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/oathswornclone:$(date +'%Y-%m-%d')
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/oathswornclone:$(date +'%Y-%m-%d')
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'oathswornclone'
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/oathswornclone:$(date +'%Y-%m-%d')
